import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    'intro',
    {
      type: 'category',
      label: 'Reference',
      link: { type: 'generated-index' },
      items: [{ type: 'autogenerated', dirName: 'reference' }],
    }
  ],
};

export default sidebars;